#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['my_add']

#Cell
def my_add(a, b):
    """Customly defined add function"""
    return a + b